### ISSUE TITLE
Possible Typo

### ISSUE THREAD

**Issue by rydurham** [snaptoken/kilo-tutorial#19]
Hello!  Thank you for putting together this fantastic tutorial - I am really enjoying working my way through it. 

I think I may have found a typo in step 132.  Currently the line is ```if (cur_rx > rx) return cx;``` but I think it should be ```if (cur_rx > cx) return cx;``` instead.   Does that sound right?

Thanks again!

**Comment by yjerem** [comment]
Hmm. I don't think `if (cur_rx > cx) return cx;` is right. If it was like that, then it looks like the function would always return `0` (because on the first iteration `cx` is `0` and we immediately increment `cur_rx` to at least `1`). It would also leave the `rx` argument unused.

The function is supposed to convert `rx` into its corresponding `cx` value. It does that by converting every possible `cx` value to its corresponding rx value (in `cur_rx`), until it finds a `cx` that corresponds to the passed-in `rx` value. Does that all make sense? (It's hard to come up with non-confusing variable names here...)

**Comment by rydurham** [comment]
Yes!  That makes total sense - thanks for the clarification!
