### ISSUE TITLE
Made a small mistake but don't really understand why it's mistake

### ISSUE THREAD

**Issue by cassepipe** [snaptoken/kilo-tutorial#35]
Hi ! Not sure if this is the right place to post this but I don't understand why this code is correct and the one under is not (--> Ctrl + 'q' no longer works). 
My rationale is the read() function reads one byte, puts it into the c variable, then if no error occurs read() is evaluated again (so the evaluation takes place before the assignment ?) . Since we only typed one character, it is the end of the stdin file, read() evaluates to 1, the while loop stops and the function returns c.
But with such a reasonning the second piece of code should not behave diferently. What have I wrong ?

I have tried to read the [read() linux man page](https://linux.die.net/man/3/read) but it is too low-level for me to understand much of it. 

Thanks in advance

```

char editorReadKey() {
  int nread;
  char c;
  while ((nread = read(STDIN_FILENO, &c, 1)) != 1) {
    if (nread == -1 && errno != EAGAIN) die("read");
  }
  return c;
}
```

and 

```

char editorReadKey() {
        int nread;
        char c;
        while ((nread = read(STDIN_FILENO, &c, 1)) != 1) {
                if (nread == -1 && errno != EAGAIN) die("read");
                return c;
  }
  
}
```

**Comment by yjerem** [comment]
Hi there! `read()` returns the number of bytes that it successfully read, or `-1` if there was an error. In this case we're asking it to read just 1 byte, so there are three possible return values:

* `1` means it successfully read 1 byte into `c`. In that case our work is done and we return from the function.
* `0` means there was no input to read. The way `kilo` is set up, `read()` will wait 0.1 seconds and if the user doesn't press a key in that time, it will timeout and return `0`. So we keep calling `read()` in a loop until they do press a key.
* `-1` means there was an error. On some platforms, when the `read()` timeouts it returns `-1` instead of `0`, with a special error code of `EAGAIN` - this isn't really an error, it's just that platform's way of timing out, so we treat that the same as the `0` case. For all other error codes, we exit.

The code for this is very dense and takes some shortcuts so it can be hard to read... Here is a more readable version that might help show what's going on:

```c
char editorReadKey() {
  char c;
  while (1) {
    int num_bytes_read = read(STDIN_FILENO, &c, 1);

    int is_success = (num_bytes_read == 1);
    int is_timeout = (num_bytes_read == 0)
                  || (num_bytes_read == -1 && errno == EAGAIN);
    int is_error = (num_bytes_read == -1 && !is_timeout);

    if (is_success) {
      return c;
    } else if (is_timeout) {
      // user hasn't pressed a key yet. try reading again in the next iteration.
    } else if (is_error) {
      die("read");
    }
  }
}
```

So the reason your 2nd example isn't working is that it returns after only calling `read()` once, whether or not the user pressed a key in those 0.1 seconds. What you want is to keep calling `read()` every 0.1 seconds until the user presses a key, and then return the key that they pressed.

Hope that helps!

**Comment by cassepipe** [comment]
Thank you so much for putting the time to craft such a good answer.
The information I thought I had assimilated correctly was in fact a bit scrambled.
