### ISSUE TITLE
Expand on Step 6 and Explain why the Order of Declaration is Important

### ISSUE THREAD

**Issue by ocelotStride** [snaptoken/kilo-tutorial#50]
I'm new to C and whenever I follow these tutorials I try different versions of the code to see if order matters. Here are two examples of code I tried which fail, but I'm not sure why they fail.

```
struct termios orig;

void DisableRawMode() {
	tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig);
}

void EnableRawMode() {
	struct termios raw = orig; /* Placing the struct declaration here breaks it */

	tcgetattr(STDIN_FILENO, &orig);
	atexit(DisableRawMode);

	raw.c_lflag &= ~(ECHO);

	tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
}
```

```
struct termios orig;

void DisableRawMode() {
	tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig);
}

void EnableRawMode() {
	struct termios raw; /* Making a fresh copy works but causes odd behaviour in the shell after the program ends */

	tcgetattr(STDIN_FILENO, &orig);
	atexit(DisableRawMode);

	raw.c_lflag &= ~(ECHO);

	tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
}
```

I'm curious about why this matters. My assumption is that in the second example, `struct termios raw = orig;` is actually making a pointer to the original and not a copy?

**Comment by paigeruten** [comment]
In both examples, `raw` is an uninitialized struct (`orig` is also uninitialized in the first example). This means it'll contain whatever happens to be in memory wherever it's stored, which could be random 1's and 0's, or just all 0's. Either way, it's probably causing `tcsetattr()` to set some weird terminal attributes. That's why we need to initialize the struct with `tcgetattr()` first.

`raw` and `orig` are separate structs in both examples - when you do `raw = orig`, you are copying the `orig` struct to the `raw` struct. In the first example, the copy is happening too early when `orig` is still uninitialized.

Hope that helps!
